### ISSUE TITLE
TPC-DS Q44 regression for the " Mixed size objects" dataset

### ISSUE THREAD

**Issue by oleg-lvovitch-aws** [awslabs/analytics-accelerator-s3#173]
### Analytics Accelerator Library for Amazon S3 Version

0.0.1

### AWS Region

`us-east-1`, though it applies broadly. 

### Describe the running environment

TPC DS benchmarking 

### What happened?

Q44 shows 8% regression by comparison with the baseline. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ahmarsuhail** [comment]
This has now been resolved with https://github.com/awslabs/analytics-accelerator-s3/pull/189, and released with v0.0.2 https://github.com/awslabs/analytics-accelerator-s3/releases/tag/v0.0.2
