### ISSUE TITLE
`S3SeekableInputStream.seek` doesn't allow seeking past the end of the stream

### ISSUE THREAD

**Issue by oleg-lvovitch-aws** [awslabs/analytics-accelerator-s3#83]
This is not the case for [S3A ](https://github.com/apache/hadoop/blob/f6c45e0bcf4aeaba31515e548dcc98b33245fe0e/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L325) and [S3FileIO](https://github.com/apache/iceberg/blob/f1076494c807447484b5a154b242611e98e3b582/aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java#L83). 

We should be able to support the same behavior

**Comment by fuatbasik** [comment]
Release 0.0.2 includes this change. Closing.
